### ISSUE TITLE
Change locale using header?

### ISSUE THREAD

**Issue by ghost** [BenConstable/laravel-localize-middleware#1]
In addition to the other methods would be cool to have another way to set the locale. 

Via `Accept-Language` header maybe?

**Comment by BenConstable** [comment]
Great idea - that was already on my todo list actually so I'll try and get it added soon.

**Comment by BenConstable** [comment]
This is in place now, as of 390bb479adfd6ab17a831748fd0d06a4e02ae77d and the [v1.1.0](https://github.com/BenConstable/laravel-localize-middleware/releases/tag/v1.1.0) release. I've added a [new section to the readme](https://github.com/BenConstable/laravel-localize-middleware#determining-the-locale-from-a-request-header), so check that out for more info.

Thanks for the suggestion!
