### ISSUE TITLE
Precedence in determiners

### ISSUE THREAD

**Issue by dionysiosarvanitis** [BenConstable/laravel-localize-middleware#2]
It would be nice if we could set a precedence in determiners. Eg. first check for a cookie and if not exists then check for a parameter, then for a session key and finally for a header attribute.

**Comment by BenConstable** [comment]
Thanks for the suggestion, it's something I've thought about actually and I'll try and get it built soon. I'll leave this issue open until then, and would welcome a PR if yourself or anyone else fancies a go.

**Comment by shadoWalker89** [comment]
+1

**Comment by BenConstable** [comment]
Hi @dionysiosarvanitis and @shadoWalker89 - I've added this functionality, so check out the updated README:

https://github.com/BenConstable/laravel-localize-middleware#using-multiple-determiners

Let me know what you think! I'll try to release a new version of the package tomorrow, but for now `dev-master` has the changes.

**Comment by BenConstable** [comment]
FYI, the relevant commit is 7925a09795e488f983d76579205238bddf1d432d if you want to have a look at the code.

**Comment by BenConstable** [comment]
This functionality is now in place as of [v1.2.0](https://github.com/BenConstable/laravel-localize-middleware/releases/tag/v1.2.0).

**Comment by dionysiosarvanitis** [comment]
That's great news! Thanks a lot @BenConstable. 

I also noticed that header's `determineLocale` should probably change a little. Since Accept-Language may include some [language-range](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.4) information we can end up with something like `da, en-gb;q=0.8, en;q=0.7` for `Accept-Language` header.

What do you think about this:

``` php
public function determineLocale(Request $request)
{
    $header = $request->header($this->header, $this->fallback);

    $accepts = explode(',', $header);

    // Turn en-gb into en
    return  ! isset($accepts[0]) ?: substr($accepts[0], 0, 2);
}
```

**Comment by BenConstable** [comment]
No worries. Thanks for bringing that to my attention - I've created issue #3 to track this. The code looks like a good start, I'll look at getting an implementation sorted soon.
