### ISSUE TITLE
The "dynamic" route prefix {$locale} seems to be not ever captured...

### ISSUE THREAD

**Issue by cirdog** [BenConstable/laravel-localize-middleware#5]
Hi, to the Author & all Users,

I've tried it and it doesn't work, and the "dynamic prefix" {$locale} seems to be not ever captured.

```
BenConstable\Localize\Determiners\Parameter

public function determineLocale(Request $request)
    {
        return $request->input($this->requestParam, $this->fallback);
    }
```

1) The $locale is not captured within the $request->input array.
2) In fact it was captured in the $request->segments() array.
3) But it's not under the name ($locale), instead it's just simply $segment[1] **(EDIT: corrected index)** if I put it there.

This package has its strength over Waavi/Translate, it's more organized, has "stacked" drivers, and it doesn't have the "string/model translation" that I don't need for now. But its weakness is that all the "default locale redirection" & "route integrity checks" are being left out, making it way less robust in handling most common routing cases.

I'll planning to either fork it or issue PR to enhance it. If the Author is still active here maybe we can chat. I don't have much free time to spare besides work, but just happen that I need it so why not share it too? (only if I'm confident that my stuff works in the end though...)

Thanks.

**Comment by BenConstable** [comment]
Thanks for bringing this to my attention, that's definitely a bug and I'll look at getting it sorted as soon as I can 👍 

Regarding the additional features you mentioned, the purpose of this package is solely to set the application locale from request data - nothing more. I wouldn't accept a PR to enhance the package beyond its scope, but do feel free to use it as base to build your own package.

**Comment by cirdog** [comment]
Thanks Ben! All noted.

And I'm using Laravel 5.4 while I encountered this bug. 

I'll test it against 5.2 again (my other older site).

Thanks again for your sharing.
